# Generated by Django 4.2.2 on 2023-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_stockincrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockincrease',
            name='unit',
            field=models.IntegerField(blank=True),
        ),
    ]
