# Generated by Django 4.2.2 on 2023-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_alter_stockincrease_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockincrease',
            name='month',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockincrease',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
