# Generated by Django 4.2.2 on 2023-07-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0004_stockincrease_month_stockincrease_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=50)),
                ('unit', models.IntegerField(blank=True)),
                ('month', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
