# Generated by Django 4.2.2 on 2023-07-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdonor',
            name='birthday_check',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
