# Generated by Django 4.2.2 on 2023-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0006_newdonor_birthday_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdonor',
            name='home_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
