# Generated by Django 4.2.2 on 2023-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0007_alter_newdonor_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdonor',
            name='count',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
