# Generated by Django 4.2.2 on 2023-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0008_newdonor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdonor',
            name='due_d',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='newdonor',
            name='due_m',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
