# Generated by Django 4.2.2 on 2023-07-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0010_remove_newdonor_due_d_remove_newdonor_due_m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdonor',
            old_name='countdown',
            new_name='day',
        ),
        migrations.AddField(
            model_name='newdonor',
            name='month',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
