# Generated by Django 4.2.2 on 2023-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0012_remove_newdonor_day_remove_newdonor_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdonor',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='newdonor',
            name='due_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
