# Generated by Django 4.2.2 on 2023-07-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0013_newdonor_date_newdonor_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdonor',
            name='lga',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
